### PR TITLE
misc bib fixes - also noting URL not found

### PR DESCRIPTION
**Pull request by danielskatz**
http://www.ros.org/urdf/ doesn't exist - please fix it to what it should be.

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
http://wiki.ros.org/urdf/ should be the right one.

**Comment by danielskatz** [comment]
thanks @ipa-mdl , I've added this to the PR now

**Comment by bmagyar** [comment]
Thanks a lot for fixing these!

**Comment by bmagyar** [comment]
How did I end up copying the bibs with the wrong format? I exported them from google scholar.

Sorry about the URDF one, that should probably be updated with the existing entry on their side as well, I only took the reference but didn't check the link. (it comes from moving the wiki under the subdomain)

**Pull request merged**
